-- MySQL Script generated by MySQL Workbench
-- Thu Jul  4 17:18:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `id_paciente` INT NOT NULL,
  `id_cpf` INT NOT NULL,
  `nome_paciente` VARCHAR(80) NULL,
  `genero_paciente` CHAR(1) NULL,
  `data_nasc` DATE NULL,
  PRIMARY KEY (`id_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Médico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Médico` (
  `id_crm` INT NOT NULL,
  `nome` VARCHAR(50) NULL,
  `genero` CHAR(1) NULL,
  `endereco` VARCHAR(80) NULL,
  `telefone` VARCHAR(15) NULL,
  `esp_medica` VARCHAR(50) NULL,
  `fk_med_paci` INT NOT NULL,
  PRIMARY KEY (`id_crm`, `fk_med_paci`),
  INDEX `fk_med_paci` (`fk_med_paci` ASC) VISIBLE,
  CONSTRAINT `fk_med_paci`
    FOREIGN KEY (`fk_med_paci`)
    REFERENCES `mydb`.`Paciente` (`fk_paci_med`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consulta` (
  `id_consulta` INT NOT NULL,
  `data_consulta` DATE NULL,
  `hora_consulta` TIME NULL,
  `Medico_id_medico` INT NOT NULL,
  `Paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_consulta`, `Medico_id_medico`, `Paciente_id_paciente`),
  INDEX `fk_consulta_medico` (`Medico_id_medico` ASC) VISIBLE,
  INDEX `fk_consulta_paciente` (`Paciente_id_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_consulta_medico`
    FOREIGN KEY (`Medico_id_medico`)
    REFERENCES `mydb`.`Medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Paciente1`
    FOREIGN KEY (`Paciente_id_paciente`)
    REFERENCES `mydb`.`Paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medico` (
  `id_medico` INT NOT NULL,
  `crm_medico` INT NOT NULL,
  `nome_medico` VARCHAR(80) NULL,
  `genero_medico` CHAR(1) NULL,
  `especialidade_medica` VARCHAR(100) NULL,
  PRIMARY KEY (`id_medico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `id_paciente` INT NOT NULL,
  `id_cpf` INT NOT NULL,
  `nome_paciente` VARCHAR(80) NULL,
  `genero_paciente` CHAR(1) NULL,
  `data_nasc` DATE NULL,
  PRIMARY KEY (`id_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consulta` (
  `id_consulta` INT NOT NULL,
  `data_consulta` DATE NULL,
  `hora_consulta` TIME NULL,
  `Medico_id_medico` INT NOT NULL,
  `Paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_consulta`, `Medico_id_medico`, `Paciente_id_paciente`),
  INDEX `fk_consulta_medico` (`Medico_id_medico` ASC) VISIBLE,
  INDEX `fk_consulta_paciente` (`Paciente_id_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_consulta_medico`
    FOREIGN KEY (`Medico_id_medico`)
    REFERENCES `mydb`.`Medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Paciente1`
    FOREIGN KEY (`Paciente_id_paciente`)
    REFERENCES `mydb`.`Paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone_medico` (
  `id_telefone_medico` INT NOT NULL,
  `fone_residencial` VARCHAR(15) NULL,
  `fone_celular` VARCHAR(15) NULL,
  `Medico_id_medico` INT NOT NULL,
  PRIMARY KEY (`id_telefone_medico`, `Medico_id_medico`),
  INDEX `fk_telefone_medico_medico` (`Medico_id_medico` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_medico_Medico1`
    FOREIGN KEY (`Medico_id_medico`)
    REFERENCES `mydb`.`Medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco_medico` (
  `id_end_medico` INT NOT NULL,
  `rua` VARCHAR(100) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(80) NULL,
  `bairro` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NULL,
  `estado` VARCHAR(80) NULL,
  `cep` VARCHAR(10) NULL,
  `Medico_id_medico` INT NOT NULL,
  PRIMARY KEY (`id_end_medico`, `Medico_id_medico`),
  INDEX `fk_endereco_medico_medico` (`Medico_id_medico` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_medico_Medico1`
    FOREIGN KEY (`Medico_id_medico`)
    REFERENCES `mydb`.`Medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Receita_medica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Receita_medica` (
  `id_receita_medica` INT NOT NULL,
  `medicacao` VARCHAR(100) NULL,
  `dosagem` VARCHAR(100) NULL,
  `via_administracao` VARCHAR(50) NULL,
  `forma_administracao` VARCHAR(80) NULL,
  `tempo_uso` VARCHAR(50) NULL,
  `Consulta_id_consulta` INT NOT NULL,
  `Consulta_Medico_id_medico` INT NOT NULL,
  `Consulta_Paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_receita_medica`, `Consulta_id_consulta`, `Consulta_Medico_id_medico`, `Consulta_Paciente_id_paciente`),
  INDEX `fk_receita_medica_consulta` (`Consulta_id_consulta` ASC, `Consulta_Medico_id_medico` ASC, `Consulta_Paciente_id_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_Receita_medica_Consulta1`
    FOREIGN KEY (`Consulta_id_consulta` , `Consulta_Medico_id_medico` , `Consulta_Paciente_id_paciente`)
    REFERENCES `mydb`.`Consulta` (`id_consulta` , `Medico_id_medico` , `Paciente_id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone_paciente` (
  `id_telefone_paciente` INT NOT NULL,
  `fone_residencial` VARCHAR(15) NULL,
  `fone_celular` VARCHAR(15) NULL,
  `Paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_telefone_paciente`, `Paciente_id_paciente`),
  INDEX `fk_telefone_paciente_paciente` (`Paciente_id_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_paciente_Paciente1`
    FOREIGN KEY (`Paciente_id_paciente`)
    REFERENCES `mydb`.`Paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
